name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        target:
          - tags: zhongruoyu/homebrew-aarch64-linux:ubuntu22.04,zhongruoyu/homebrew-aarch64-linux:latest
            version: 22.04
          - tags: zhongruoyu/homebrew-aarch64-linux:ubuntu20.04
            version: 20.04
          - tags: zhongruoyu/homebrew-aarch64-linux:ubuntu18.04
            version: 18.04
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          tags: ${{ matrix.target.tags }}
          platforms: linux/aarch64
          build-args: |
            version=${{ matrix.target.version }}
          push: true
